config/routes.rb
FlatspacePlugins::Application.routes.draw do
  match "/auth/facebook/callback" => "sessions#create"
  match "/sign_out" => "sessions#destroy", as: :sign_out

  resources :plugins
  root to: "plugins#index"
end

app/models/plugin.rb
class Plugin
  include Mongoid::Document
  include Mongoid::Timestamps
  field :title,       type: String
  field :description, type: String
  belongs_to :user
  
  validates_presence_of :title, :description, :user
end

app/models/user.rb
class User
  include Mongoid::Document
  field :name,        type: String
  field :facebook_id, type: String
  
  validates_presence_of :name, :facebook_id
  
  def self.find_by_facebook_id(facebook_id)
    where(facebook_id: facebook_id).first
  end
  
  def self.create_with_omniauth(auth)
    create! do |user|
      user.facebook_id = auth["uid"]
      user.name        = auth["info"]["name"]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :set_referer
  protect_from_forgery
  helper_method :current_user, :user_signed_in?
  
  private
    def user_signed_in?
      !!session[:user_id]
    end
  
    def current_user
      @current_user ||= User.find(session[:user_id]) if user_signed_in?
    end
    
    def authenticate_user!
      redirect_to '/auth/facebook' unless user_signed_in?
    end
    
    def set_referer
      session[:return_to] ||= []
      session[:return_to] << request.path
      session[:return_to].shift if session[:return_to].size > 5
    end
end

app/controllers/plugins_controller.rb
class PluginsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  
  def index
    @plugins = Plugin.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @plugins }
    end
  end

  def show
    @plugin = Plugin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @plugin }
    end
  end

  def new
    @plugin = Plugin.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @plugin }
    end
  end

  def edit
    @plugin = Plugin.find(params[:id])
  end

  def create
    @plugin = Plugin.new(params[:plugin])
    @plugin.user = current_user

    respond_to do |format|
      if @plugin.save
        format.html { redirect_to @plugin, notice: 'Plugin was successfully created.' }
        format.json { render json: @plugin, status: :created, location: @plugin }
      else
        format.html { render action: "new" }
        format.json { render json: @plugin.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @plugin = Plugin.find(params[:id])

    respond_to do |format|
      if @plugin.update_attributes(params[:plugin])
        format.html { redirect_to @plugin, notice: 'Plugin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @plugin.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @plugin = Plugin.find(params[:id])
    @plugin.destroy

    respond_to do |format|
      format.html { redirect_to plugins_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :set_referer
  
  def create
    auth = request.env["omniauth.auth"]
    user = User.find_by_facebook_id(auth["uid"]) || User.create_with_omniauth(auth)
    session[:user_id] = user.to_param
    redirect_to session[:return_to][-1], notice: "Signed in!"
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Signed out!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plugins_helper.rb
module PluginsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "FlatspacePlugins"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/favicon.ico" rel="shortcut icon")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114")

  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "Flatspace Plugins", root_url, class: 'brand'
          .container.nav-collapse
            %ul.nav
              %li= link_to "Plugin List", plugins_path
              %li= link_to "+ Add Plugin", new_plugin_path
              %li= link_to "About", ""
              %li
                - if user_signed_in?
                  = link_to "Sign Out", sign_out_path
                - else
                  = link_to "Sign in with Facebook", "/auth/facebook"

    .container
      .content
        .row
          .span12
            = yield    
      %footer
        %p created by Stefano Diem Benatti @ HeavenStudio
    = javascript_include_tag "application"


app/views/plugins/_form.html.haml
= form_for @plugin, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :title, :class => 'control-label'
    .controls
      = f.text_field :title, :class => 'text_field'
  .control-group
    = f.label :description, :class => 'control-label'
    .controls
      = f.text_area :description, :class => 'text_area'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), plugins_path, :class => 'btn'

app/views/plugins/edit.html.haml
- model_class = @plugin.class
%h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/plugins/index.html.haml
- model_class = Plugin.new.class
%h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:title)
      %th(colspan=2)= model_class.human_attribute_name(:created_at)
  %tbody
    - @plugins.each do |plugin|
      %tr
        %td= link_to plugin.title, plugin
        %td=l plugin.created_at
        %td
          - if user_signed_in? && current_user == plugin.user
            = link_to t('.edit', default: t("helpers.links.edit")), edit_plugin_path(plugin), class: 'btn btn-mini'
            = link_to t('.destroy', default: t("helpers.links.destroy")), plugin_path(plugin), method: :delete, confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')), class: 'btn btn-mini btn-danger'

app/views/plugins/new.html.haml
- model_class = @plugin.class
%h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/plugins/show.html.haml
- model_class = @plugin.class
%h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:title) + ':'
  %br
  = @plugin.title
%p
  %strong= model_class.human_attribute_name(:description) + ':'
  %br
  = simple_format @plugin.description

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), plugins_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_plugin_path(@plugin), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), plugin_path(@plugin), :method => "delete", :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-danger'